repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
  - id: pyupgrade
    args: [--py38-plus]
- repo: https://github.com/psf/black
  rev: 23.10.1
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear==22.12.6]
- repo: https://github.com/asottile/blacken-docs
  rev: 1.16.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==22.1.0]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.6.1
  hooks:
  - id: mypy
    files: ^src/apispec_webframeworks/
    additional_dependencies: ["Flask==2.3.3", "tornado>=6", "bottle", "apispec[yaml]>=5.2.1", types-setuptools]
