repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.5
  hooks:
    - id: ruff
    - id: ruff-format
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.28.1
  hooks:
    - id: check-github-workflows
    - id: check-readthedocs
- repo: https://github.com/asottile/blacken-docs
  rev: 1.16.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==23.12.1]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0
  hooks:
  - id: mypy
    files: ^src/apispec_webframeworks/
    additional_dependencies: ["Flask==2.3.3", "tornado>=6", "bottle", "apispec[yaml]>=5.2.1", types-setuptools]
